name: nuget-publish
run-name: ${{ github.ref_name }}.${{ github.run_number }}

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pack:
    name: Pack & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Run GitVersion
        run: |
          dotnet dotnet-gitversion /output json
          echo "SEM_VERSION=$(dotnet dotnet-gitversion /showvariable SemVer)" >> "$GITHUB_ENV"

      - name: Build (Release)
        run: dotnet build --configuration Release --verbosity minimal

      - name: Pack
        run: >
          dotnet pack src/DotnetConventions/DotnetConventions.csproj
          --configuration Release
          --no-build
          -p:Version=${{ env.SEM_VERSION }}
          --output ./artifacts

      - name: Upload nupkg artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: ./artifacts/*.nupkg

      - name: Push to nuget.org
        run: dotnet nuget push "./artifacts/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate

      - name: Git tag
        run: |
          set -e
          git tag "$SEM_VERSION"
          git push origin "$SEM_VERSION"
